function myinfo(){
    console.log("ayush dixit");
}
function myaddress(){
    console.log("firozabad");
}

module.exports={myinfo};
module.exports={myaddress};



// sync call stack se direct response deta h
// async call stack se event thread m chala jayega fer woh event queue m jata h fer event loop m jata h
// event loop ye dikhta h kon pehle execute hoga jaise koi async 2sec h aur ek 1 sec toh 1 sec wala execute event loop k through hoga
// modal view controller in sab ko kehte h 


// when we install third party it can store in package.json

// package-lock.json-automatically generated by npm improve speed and consistency lock the exact version of package it carry general info ki sub dependency ki info

// package.json->used to store data in key-value format created by developer it carry general info

// lazy loading and reconsiration and hot reload

// hot  reload -> kisi framework k part nhi hota h kisi tool k through use hota hot reload hamare code k change k sath terminal ko auto restart krta h

// lazy-loading->runtime environment ye saare framework m h third party component m hota

// recon->ye virtual dom ko physical dom ko bej deta h inbuilt feature of react

// node --watch f.js ->in built in node after 18.11 version

// fs-> database m data loss aur data less storage toh storage waste hota h ye iska disadvantage yaha fer aaya fs jo isko overcome krega

// fs give me power jisse hum n no.. of opera.. perform kr ske like read write...

//  mod ->define kon kya kaam krega
// flag->
// read write append ye sab pdna h




